const ResponseStates = {

    NO_COMMAND: 0,
    COMMAND_STRING: 1,
    COMMAND_HEADER: 2,
    COMMAND_RESPONSE: 3,
    COMMAND_FOOTER: 4
};

module.exports.ResponseStates = ResponseStates;

const AURORA_USB_VID = "0x0483";
module.exports.AURORA_USB_VID = AURORA_USB_VID;

const COMMAND_PROMPT = "\n# ";
module.exports.COMMAND_PROMPT = COMMAND_PROMPT;

const COMMAND_STRING_MAX_LENGTH = 128;
module.exports.COMMAND_STRING_MAX_LENGTH = COMMAND_STRING_MAX_LENGTH;

const COMMAND_HEADER_MIN_LENGTH = 64;
module.exports.COMMAND_DIVIDER_MIN_LENGTH = COMMAND_HEADER_MIN_LENGTH;

const COMMAND_HEADER_MAX_LENGTH = 128;
module.exports.COMMAND_DIVIDER_MAX_LENGTH = COMMAND_HEADER_MAX_LENGTH;

const COMMAND_HEADER_SUCCESS_CHAR = '-';
module.exports.COMMAND_DIVIDER_SUCCESS_CHAR = COMMAND_HEADER_SUCCESS_CHAR;

const COMMAND_HEADER_ERROR_CHAR = '~';
module.exports.COMMAND_DIVIDER_ERROR_CHAR = COMMAND_HEADER_ERROR_CHAR;

const DataTypes = {

    BOOL: 1,
    CHAR: 2,
    UINT8: 3,
    INT8: 4,
    UINT16: 5,
    INT16: 6,
    UINT32: 7,
    INT32: 8,
    FLOAT: 9,
    STR: 10,
    PTR: 11
};

module.exports.DataTypes = DataTypes;